@echo off
mkdir "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\github_integration"
mkdir "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\routes"
mkdir "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\data_pipeline"
mkdir "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\ui"
mkdir "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\utils"
mkdir "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\static"

move "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\backend\app\analysis_engine" "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\analysis_engine"
move "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\backend\app\api\routes.py" "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\routes\api.py"
move "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\backend\app\api\webhook.py" "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\routes\webhook.py"
move "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\backend\app\services\github_service.py" "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\github_integration\github_service.py"
move "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\backend\app\services\analysis_service.py" "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\analysis_engine\analysis_service.py"
move "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\backend\app\services\cache_service.py" "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\utils\cache_service.py"
move "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\backend\app\core\config.py" "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\config.py"
move "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\backend\app\core\redis_client.py" "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\database.py"
move "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\backend\app\schemas\models.py" "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\models.py"
move "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\backend\app\main.py" "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\main.py"
move "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\backend\app\worker.py" "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\worker.py"
move "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\backend\requirements.txt" "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\requirements.txt"
move "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\backend\docker-compose.yml" "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\docker-compose.yml"
move "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\backend\.env.example" "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\.env.example"
move "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\backend\test_preview.py" "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\test_preview.py"
move "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\backend\test_service.py" "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\test_service.py"

rmdir /s /q "c:\Users\Vansh Kaushal\OneDrive\Desktop\CODE\college project\backend"
