"""
Celery worker for asynchronous processing of GitHub webhooks.
"""

from celery import Celery
import logging
from config import settings
from analysis_engine import review_code_diff, calculate_metrics

from github_integration.github_service import fetch_pr_context, post_pr_comment

logger = logging.getLogger(__name__)

# Create celery app
celery_app = Celery(
    "worker",
    broker=settings.REDIS_URL,
    backend=settings.REDIS_URL
)

# Configure Celery
celery_app.conf.update(
    task_serializer="json",
    accept_content=["json"],
    result_serializer="json",
    timezone="UTC",
    enable_utc=True,
    broker_connection_retry_on_startup=True,
)


def _generate_markdown_review(score: int, alignment: int, risk: str, issues: list) -> str:
    """Format the review output as a markdown payload for GitHub."""
    
    # Emoji mapping for severity
    severities = {
        "critical": "🚨",
        "high": "🔴",
        "medium": "🟡",
        "low": "🔵"
    }

    md = f"## 🤖 SmartCode Review\n\n"
    md += f"### PR Approval Confidence: {score}/100\n\n"
    md += f"### Requirement Alignment: {alignment}\n\n"
    md += f"### Risk Level: {risk.title()}\n\n"
    
    md += "### Issues Found:\n\n"
    if not issues:
        md += "✅ No major security issues, bugs, or anti-patterns detected.\n\n"
    else:
        for issue in issues:
            sev = issue.get("severity", "low").lower()
            icon = severities.get(sev, "🔵")
            md += f"- {icon} **{issue.get('title', 'Issue')}**: {issue.get('description', '')}"
            if "file" in issue and issue["file"]:
                md += f" (`{issue['file']}`)\n"
            else:
                md += "\n"
    
    md += "\n---\n*Generated by SmartCode Decision Intelligence Engine*\n"
    return md


@celery_app.task(name="process_pr_task", bind=True, max_retries=3)
def process_pr_task(self, repo_full_name: str, pr_number: int, installation_id: int):
    """
    Background task to analyze a pull request utilizing the AI engine.
    """
    logger.info(f"Started processing PR #{pr_number} for {repo_full_name} (Installation: {installation_id})")
    try:
        # 1. Fetch Real Context
        logger.info("Fetching real PR context from GitHub...")
        pr_context = fetch_pr_context(repo_full_name, pr_number)
        
        # 2. Call LLM for analysis using context dict
        logger.info("Triggering LLM Review...")
        report = review_code_diff(pr_context)
        
        # 3. Calculate normalized metrics using unmodified logic
        metrics = calculate_metrics(report)
        logger.info(f"Generated Metrics: {metrics}")
        
        # Extract fields for markdown
        score = metrics.get("confidence_score", 50)
        alignment = report.get("requirement_alignment_score", 50)
        risk = report.get("risk_level", "Unknown")
        issues = report.get("issues", [])

        # 4. Generate Markdown
        review_body = _generate_markdown_review(score, alignment, risk, issues)
        
        # 5. Post review comment back to PR
        logger.info("Posting review to GitHub...")
        post_success = post_pr_comment(repo_full_name, pr_number, review_body)
        if not post_success:
            logger.warning("Failed to post PR comment.")
        
        logger.info(f"Finished processing PR #{pr_number} for {repo_full_name}")
        return {"status": "success", "repo": repo_full_name, "pr": pr_number, "metrics": metrics}
    except Exception as exc:
        logger.error(f"Error processing PR #{pr_number} for {repo_full_name}: {exc}")
        self.retry(exc=exc, countdown=60)  # Retry after 1 minute on failure
